CREATE TABLE IF NOT EXISTS `customskinfac` (
  `factionid` int(11) NOT NULL,
  `FactionSkin1` int(11) NOT NULL DEFAULT 0,
  `FactionSkin2` int(11) NOT NULL DEFAULT 0,
  `FactionSkin3` int(11) NOT NULL DEFAULT 0,
  `FactionSkin4` int(11) NOT NULL DEFAULT 0,
  `FactionSkin5` int(11) NOT NULL DEFAULT 0,
  `FactionSkin6` int(11) NOT NULL DEFAULT 0,
  `FactionSkin7` int(11) NOT NULL DEFAULT 0,
  `FactionSkin8` int(11) NOT NULL DEFAULT 0,
  `FactionSkin9` int(11) NOT NULL DEFAULT 0,
  `FactionSkin10` int(11) NOT NULL DEFAULT 0,
  `FactionSkin11` int(11) NOT NULL DEFAULT 0,
  `FactionSkin12` int(11) NOT NULL DEFAULT 0,
  `FactionSkin13` int(11) NOT NULL DEFAULT 0,
  `FactionSkin14` int(11) NOT NULL DEFAULT 0,
  `FactionSkin15` int(11) NOT NULL DEFAULT 0,
  `FactionSkin16` int(11) NOT NULL DEFAULT 0,
  `FactionSkin17` int(11) NOT NULL DEFAULT 0,
  `FactionSkin18` int(11) NOT NULL DEFAULT 0,
  `FactionSkin19` int(11) NOT NULL DEFAULT 0,
  `FactionSkin20` int(11) NOT NULL DEFAULT 0,
  `FactionSkin21` int(11) NOT NULL DEFAULT 0,
  `FactionSkin22` int(11) NOT NULL DEFAULT 0,
  `FactionSkin23` int(11) NOT NULL DEFAULT 0,
  `FactionSkin24` int(11) NOT NULL DEFAULT 0,
  `FactionSkin25` int(11) NOT NULL DEFAULT 0,
  `FactionSkin26` int(11) NOT NULL DEFAULT 0,
  `FactionSkin27` int(11) NOT NULL DEFAULT 0,
  `FactionSkin28` int(11) NOT NULL DEFAULT 0,
  `FactionSkin29` int(11) NOT NULL DEFAULT 0,
  `FactionSkin30` int(11) NOT NULL DEFAULT 0,
    PRIMARY KEY
      (factionid)
);