CREATE TABLE IF NOT EXISTS `vehicles` (
  `VehicleDBID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `VehicleOwnerDBID` int(11) UNSIGNED NOT NULL,
  `VehicleFaction` int(11) NOT NULL DEFAULT 0,
  `VehicleModel` int(11) NOT NULL,
  `VehicleColor1` int(11) NOT NULL DEFAULT 0,
  `VehicleColor2` int(11) NOT NULL DEFAULT 0,
  `VehiclePaintjob` int(11) NOT NULL DEFAULT -1,
  `VehicleParkPosX` float NOT NULL,
  `VehicleParkPosY` float NOT NULL,
  `VehicleParkPosZ` float NOT NULL,
  `VehicleParkPosA` float NOT NULL,
  `VehicleParkInterior` int(11) NOT NULL DEFAULT 0,
  `VehicleParkWorld` int(11) NOT NULL DEFAULT 0,
  `VehiclePlates` varchar(32) NOT NULL,
  `VehicleLocked` int(11) NOT NULL,
  `VehicleComp` int(11) NOT NULL DEFAULT 0,
  `VehicleImpounded` tinyint(1) NOT NULL DEFAULT 0,
  `VehicleImpoundPosX` float NOT NULL,
  `VehicleImpoundPosY` float NOT NULL,
  `VehicleImpoundPosZ` float NOT NULL,
  `VehicleImpoundPosA` float NOT NULL,
  `VehicleSirens` int(11) NOT NULL DEFAULT 0,
  `VehicleFuel` int(11) NOT NULL DEFAULT 100,
  `VehicleDrug1` float(11) NOT NULL DEFAULT 0.0,
  `VehicleDrug2` float(11) NOT NULL DEFAULT 0.0,
  `VehicleDrug3` float(11) NOT NULL DEFAULT 0.0,
  `VehicleWeapons1` int(11) NOT NULL DEFAULT 0,
  `VehicleWeapons2` int(11) NOT NULL DEFAULT 0,
  `VehicleWeapons3` int(11) NOT NULL DEFAULT 0,
  `VehicleWeapons4` int(11) NOT NULL DEFAULT 0,
  `VehicleWeapons5` int(11) NOT NULL DEFAULT 0,
  `VehicleWeaponsAmmo1` int(11) NOT NULL DEFAULT 0,
  `VehicleWeaponsAmmo2` int(11) NOT NULL DEFAULT 0,
  `VehicleWeaponsAmmo3` int(11) NOT NULL DEFAULT 0,
  `VehicleWeaponsAmmo4` int(11) NOT NULL DEFAULT 0,
  `VehicleWeaponsAmmo5` int(11) NOT NULL DEFAULT 0,
  `VehicleBattery` float NOT NULL DEFAULT 100,
  `VehicleEngine` float NOT NULL DEFAULT 100,
  `VehicleTimesDestroyed` int(11) NOT NULL DEFAULT 0,
  `VehicleXMR` tinyint(1) NOT NULL DEFAULT 0,
  `VehicleAlarmLevel` int(11) NOT NULL DEFAULT 0,
  `VehicleLockLevel` int(11) NOT NULL DEFAULT 0,
  `VehicleImmobLevel` int(11) NOT NULL DEFAULT 1,
  `VehiclePrice` int(11) NOT NULL,
  `VehicleMod1` int(11) NOT NULL,
  `VehicleMod2` int(11) NOT NULL,
  `VehicleMod3` int(11) NOT NULL,
  `VehicleMod4` int(11) NOT NULL,
  `VehicleMod5` int(11) NOT NULL,
  `VehicleMod6` int(11) NOT NULL,
  `VehicleMod7` int(11) NOT NULL,
  `VehicleMod8` int(11) NOT NULL,
  `VehicleMod9` int(11) NOT NULL,
  `VehicleMod10` int(11) NOT NULL,
  `VehicleMod11` int(11) NOT NULL,
  `VehicleMod12` int(11) NOT NULL,
  `VehicleMod13` int(11) NOT NULL,
  `VehicleMod14` int(11) NOT NULL,
    PRIMARY KEY
        (VehicleDBID),
    FOREIGN KEY
        (VehicleOwnerDBID)
    REFERENCES
        masters(acc_dbid)
    ON DELETE
        CASCADE
    ON UPDATE
        NO ACTION
);
